# @see https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ps_controller_tabs_set:
    path: /configure-tabs/set
    methods: [GET]
    defaults:
        _controller: 'Mygooglereviews\Controller\Admin\SetGoogleReviewsController::indexAction'

ps_controller_mygooglereviews_set:
    path: /mygooglereviews/set
    methods: [GET]
    defaults:
        _controller: 'Mygooglereviews\Controller\Admin\MyTestController::indexAction'

ps_controller_ajax_get:
    path: /configure-tabs/ajaxgetplaceid
    methods: [POST, GET]
    defaults:
        _controller: 'Mygooglereviews\Controller\Admin\SetGoogleReviewsController::ajaxgetplaceidAction'
        _legacy_controller: 'ps_controller_ajax_get'

ps_controller_ajax_getreviews:
    path: /configure-tabs/ajaxgetreviews
    methods: [POST]
    defaults:
        _controller: 'Mygooglereviews\Controller\Admin\SetGoogleReviewsController::ajaxgetreviewsAction'
        _legacy_controller: 'ps_controller_ajax_getreviews'
